### ISSUE TITLE
X-axis  title is not  in the  middle  when there  is 1/2 bars  in the  chart

### ISSUE THREAD

**Issue by kety33** [krispo/angular-nvd3#144] opened 2015-06-07 10:46 UTC
Hi , 
I  am  using  nv.d3  version 1.7.1
I  have  multiBarChart  and  set  it  to  show  tilte  of the  x-axis.
When the  chert  data  contain only  one  or  two  bars the  x-axsis  title  is  not  in the  middle  of the  chart.
The code  that  calculate the  location  is :   
       axisLabel.enter().append('text').attr('class', 'nv-axislabel');
                    var w;
                    if (scale.range().length < 2) {
                        w = 0;
                    } else if (scale.range().length === 2) {
                        w = scale.range()[1];
                    } else {
                        w = scale.range()[scale.range().length-1]+(scale.range()[1]-scale.range()[0]);
                    }
                    axisLabel
                        .attr('text-anchor', 'middle')
                        .attr('y', xLabelMargin)
                        .attr('x', w/2);

and  in  case  of scale.range().length<=2  the  value of  x  is not  correct,  and the  title is moved left.
I  change the  code to  the  following  , but  i  am  not  sure  it  is  correct:
if (scale.range().length === 1) {
        w = scale.range()[0] * 2 + scale.rangeBand();
 } else if (scale.range().length === 2) {
       w = scale.rangeBand() * 2 ;
} else if ( scale.range().length > 2){
         w = scale.range()[scale.range().length-1]+(scale.range()[1]-scale.range()[0]);
};

**Comment by NameFILIP** [comment] 2015-06-24 18:43
Duplicate of https://github.com/krispo/angular-nvd3/issues/145

**Closed** 2015-06-24 18:44 UTC
Labels: duplicate
