### ISSUE TITLE
Invalid Value for <g> attribute

### ISSUE THREAD

**Issue by TylerOrtiz** [krispo/angular-nvd3#285] opened 2015-11-20 22:54 UTC
Getting this error with my simple line chart with 2 data sets :

```Error: Invalid value for <g> attribute transform="translate(NaN,NaN)"```
I'm graphing two data sets of equal length and this error happens when I toggle one of the data sets off / on. It seems to be happening with the data set that has a much larger Max Y value than the other data set. Perhaps it is trying to render the chart too quickly before it 'shrinks' down? I tried adjusting the transitionDuration and toggling the interactiveGuideline but it did not get rid of this bug. 

It seems to only happen AFTER I mouse hovered over the lines and the chart's Y axis decreases to be less than the hovered line's Y coordinate. The amount of console errors seems to suggest this because the higher I was on the Y axis the more errors occurred when toggling off the larger data set. 

HTML usage:
``` <nvd3 options="chartOptions" data="myObject.myProperty"></nvd3>```

Data population:
```  myObject.myProperty = [
		            {
		                key: "set 1",
		                values: data1,
                        disabled: false
		            }
                    ,
		            {
		                key: "set 2",
		                values: data2,
                        disabled: false
		            }
		        ];```

Options Object:
```
 $scope.chartOptions = {
                chart: {
                    type: 'lineChart', //lineWithFocusChart
                    height: 550,
                    width: 850,
                    margin : {
                        top: 20,
                        right: 20,
                        bottom: 100,
                        left: 100
                    },
                    transitionDuration: 1500,
                    x: function(d) { return d.x; },
                    y: function(d) { return d.y; },
                    useInteractiveGuideline: true,
                    dispatch: {
                        stateChange: function(e){ },
                        changeState: function(e){ },
                        tooltipShow: function(e){ },
                        tooltipHide: function(e){ }
                    },
                    xAxis: {
                        axisLabel: 'axis x',
                          tickFormat: function(d){
                            return d3.format('.02f')(d);
                        },
                    },
                    yAxis: {
                        axisLabel: 'axis y',
                        tickFormat: function(d){
                            return d3.format('.02f')(d);
                        },
                        axisLabelDistance: 0
                    },
                    // Used if a focus chart is included for lineWithFocusChart type
                    //x2Axis: {
                    //    axisLabel: 'axis x',
                    //      tickFormat: function(d){
                    //        return d3.format('.02f')(d);
                    //    },
                    //},
                    //y2Axis: {
                    //    axisLabel: 'axis y',
                    //    tickFormat: function(d){
                    //        return d3.format('.02f')(d);
                    //    },
                    //    axisLabelDistance: 0
                    //},
                    callback: function(chart){
                        //console.log("!!! lineChart callback !!!", chart);
                    }
                },
                title: {
                    enable: true,
                    text: 'My Awesome Chart'
                }
        };
```

**Comment by hxlniada** [comment] 2015-11-24 16:42
+1

**Comment by krispo** [comment] 2015-11-27 17:58
The problem is in nvd3 core. But it's already [fixed](https://github.com/novus/nvd3/issues/1373#event-475991935) in the master, so will be fixed in the next release.

**Closed by krispo** 2015-11-27 17:58 UTC
